### ISSUE TITLE
ERROR running force:source:deploy: Maximum call stack size exceeded - Started with v7.32

### ISSUE THREAD

**Issue by adnanaquib** [forcedotcom/sfdx-core#194]
7.32.0-b30e0302f0
The latest version of Salesforce CLI is throwing the Maximum call stack size exceeded issue, failing our entire production pipeline. We removed custom labels on from the manifest package so it seems to not be related to the other similar sounding issue. Please let me know how I can provide any other details you guys require

Tested out with 7.28.7-7bceba6f24 the same deployment works Command used **sfdx force:source:deploy**

**Comment by williamruemmele-sf** [comment]
Hi @adnanaquib can you provide me with any more information? such as commands run? package contents? the error thrown when using the `--dev-debug` flag at the end of the command. Any more information that you can provide will be helpful in quickly resolving the issue.

**Comment by adnanaquib** [comment]
@williamruemmele-sf 

Stack Trace:

*** Internal Diagnostic ***

RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at Function.enabled (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/debug/src/common.js:220:32)
    at createDebug (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/debug/src/common.js:119:33)
    at Object.apply (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:173:36)
    at new DefaultMetadataType (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/lib/source/metadataTypeImpl/defaultMetadataType.js:22:23)
    at new NondecomposedTypesWithChildrenMetadataType (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/lib/source/metadataTypeImpl/nondecomposedTypesWithChildrenMetadataType.js:16:1)
    at Function.getMetadataTypeFromMetadataName (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/lib/source/metadataTypeFactory.js:185:44)
    at Object.exports.loadSourceElement (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/lib/source/sourceUtil.js:192:72)
    at Object.exports.loadSourceElement (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/lib/source/sourceUtil.js:209:28)
    at Object.exports.loadSourceElement (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/lib/source/sourceUtil.js:209:28)
    at Object.exports.loadSourceElement (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/lib/source/sourceUtil.js:209:28)
    at Object.exports.loadSourceElement (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/lib/source/sourceUtil.js:209:28)
    at Object.exports.loadSourceElement (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/lib/source/sourceUtil.js:209:28)
    at Object.exports.loadSourceElement (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/lib/source/sourceUtil.js:209:28)
    at Object.exports.loadSourceElement (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/lib/source/sourceUtil.js:209:28)
    at Object.exports.loadSourceElement (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/lib/source/sourceUtil.js:209:28)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at SourceApiCommand.execute (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/lib/source/sourceApiCommand.js:47:14)
    at SourceDeployCommand.execLegacyCommand (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/ToolbeltCommand.js:148:43)
Outer stack:
    at Function.wrap (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/sfdxError.js:151:27)
    at SourceDeployCommand.catch (/Users/nasadnan/.local/share/sfdx/client/7.32.0-b30e0302f0/node_modules/salesforce-alm/dist/ToolbeltCommand.js:247:46)
******
Package Contents would be difficult for me to elaborate as we have InfoSec Requirements

Command Run 
***sfdx force:source:deploy -x manifest.xml -u <alias> -c ***

**Comment by adnanaquib** [comment]
The issue at this point was due to using specific members in Workflow type in manifest.  Using * fixed it

**Comment by jeisonmp** [comment]
I have some problema. When I used one package.xml file very big using the command "sfdx force:source:deploy" this error occurs, but when I convert path with command using "sfdx force:source:convert" and after I use command "sfdx force:mdapi:deploy" then this error not occurs.

Below you see log error:

`sfdx:SourceWorkspaceAdapter DEBUG pending change: _SourcePathInfo {
  sfdx:SourceWorkspaceAdapter   sourcePath:
  sfdx:SourceWorkspaceAdapter    'C:\\PROJETOS\\santander\\crm\\salesforce-backoffice\\force-app\\main\\default\\workflows\\EmailMessage.workflow-meta.xml',
  sfdx:SourceWorkspaceAdapter   isDirectory: false,
  sfdx:SourceWorkspaceAdapter   size: 1151,
  sfdx:SourceWorkspaceAdapter   modifiedTime: 1584598367829,
  sfdx:SourceWorkspaceAdapter   changeTime: 1584598367829,
  sfdx:SourceWorkspaceAdapter   contentHash: 'e4e31b05e095806d755ba9184fd750c9caaccfde',
  sfdx:SourceWorkspaceAdapter   isMetadataFile: true,
  sfdx:SourceWorkspaceAdapter   state: 'n',
  sfdx:SourceWorkspaceAdapter   isWorkspace: false,
  sfdx:SourceWorkspaceAdapter   isArtifactRoot: false } +5ms
  sfdx:SourceWorkspaceAdapter DEBUG pending change: _SourcePathInfo {
  sfdx:SourceWorkspaceAdapter   sourcePath: 'C:\\PROJETOS\\santander\\crm\\salesforce-backoffice',
  sfdx:SourceWorkspaceAdapter   isDirectory: true,
  sfdx:SourceWorkspaceAdapter   size: 0,
  sfdx:SourceWorkspaceAdapter   modifiedTime: 1584629952639,
  sfdx:SourceWorkspaceAdapter   changeTime: 1584629952639,
  sfdx:SourceWorkspaceAdapter   contentHash: 'e3944b9d8e3ea8a7782b17ece64831e7b7358082',
  sfdx:SourceWorkspaceAdapter   isMetadataFile: false,
  sfdx:SourceWorkspaceAdapter   state: 'n',
  sfdx:SourceWorkspaceAdapter   isWorkspace: true,
  sfdx:SourceWorkspaceAdapter   isArtifactRoot: false } +6ms
ERROR running force:source:convert:  Maximum call stack size exceeded
*** Internal Diagnostic ***

RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at Function.enabled (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\debug\src\common.js:220:32)
    at createDebug (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\debug\src\common.js:119:33)
    at Object.apply (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\@salesforce\lazy-require\lib\LazyLoader.js:173:36)
    at new DefaultMetadataType (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\source\metadataTypeImpl\defaultMetadataType.js:22:23)
    at new NondecomposedTypesWithChildrenMetadataType (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\source\metadataTypeImpl\nondecomposedTypesWithChildrenMetadataType.js:16:1)
    at new CustomLabelsMetadataType (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\source\metadataTypeImpl\customLabelsMetadataType.js:10:1)
    at Function.getMetadataTypeFromMetadataName (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\source\metadataTypeFactory.js:179:44)
    at Object.exports.loadSourceElement (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:192:72)
    at Object.exports.loadSourceElement (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:209:28)
    at Object.exports.loadSourceElement (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:209:28)
    at Object.exports.loadSourceElement (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:209:28)
    at Object.exports.loadSourceElement (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:209:28)
    at Object.exports.loadSourceElement (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:209:28)
    at Object.exports.loadSourceElement (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:209:28)
    at Object.exports.loadSourceElement (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\source\sourceUtil.js:209:28)
From previous event:
    at SourceConvertCommand.execute (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\lib\source\sourceConvertCommand.js:53:14)
    at SourceConvertCommand.execLegacyCommand (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\ToolbeltCommand.js:148:43)
Outer stack:
    at Function.wrap (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\@salesforce\core\lib\sfdxError.js:151:27)
    at SourceConvertCommand.catch (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\salesforce-alm\dist\ToolbeltCommand.js:247:46)
******

  sfdx:SourceConvertCommand ERROR [ '\u001b[1mERROR running force:source:convert: \u001b[22m',
  sfdx:SourceConvertCommand   '\u001b[31mMaximum call stack size exceeded\u001b[39m',
  sfdx:SourceConvertCommand   '\u001b[31m\u001b[39m\n\u001b[31m*** Internal Diagnostic ***\u001b[39m\n\u001b[31m\u001b[39m\n\u001b[31mRangeError: Maximum call stack size exceeded\u001b[39m\n\u001b[31m    at RegExp.test (<anonymous>)\u001b[39m\n\u001b[31m    at Function.enabled (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\debug\\src\\common.js:220:32)\u001b[39m\n\u001b[31m    at createDebug (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\debug\\src\\common.js:119:33)\u001b[39m\n\u001b[31m    at Object.apply (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\@salesforce\\lazy-require\\lib\\LazyLoader.js:173:36)\u001b[39m\n\u001b[31m    at new DefaultMetadataType (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\lib\\source\\metadataTypeImpl\\defaultMetadataType.js:22:23)\u001b[39m\n\u001b[31m    at new NondecomposedTypesWithChildrenMetadataType (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\lib\\source\\metadataTypeImpl\\nondecomposedTypesWithChildrenMetadataType.js:16:1)\u001b[39m\n\u001b[31m    at new CustomLabelsMetadataType (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\lib\\source\\metadataTypeImpl\\customLabelsMetadataType.js:10:1)\u001b[39m\n\u001b[31m    at Function.getMetadataTypeFromMetadataName (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\lib\\source\\metadataTypeFactory.js:179:44)\u001b[39m\n\u001b[31m    at Object.exports.loadSourceElement (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceUtil.js:192:72)\u001b[39m\n\u001b[31m    at Object.exports.loadSourceElement (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceUtil.js:209:28)\u001b[39m\n\u001b[31m    at Object.exports.loadSourceElement (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceUtil.js:209:28)\u001b[39m\n\u001b[31m    at Object.exports.loadSourceElement (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceUtil.js:209:28)\u001b[39m\n\u001b[31m    at Object.exports.loadSourceElement (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceUtil.js:209:28)\u001b[39m\n\u001b[31m    at Object.exports.loadSourceElement (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceUtil.js:209:28)\u001b[39m\n\u001b[31m    at Object.exports.loadSourceElement (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceUtil.js:209:28)\u001b[39m\n\u001b[31m    at Object.exports.loadSourceElement (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceUtil.js:209:28)\u001b[39m\n\u001b[31mFrom previous event:\u001b[39m\n\u001b[31m    at SourceConvertCommand.execute (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceConvertCommand.js:53:14)\u001b[39m\n\u001b[31m    at SourceConvertCommand.execLegacyCommand (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:148:43)\u001b[39m\n\u001b[31mOuter stack:\u001b[39m\n\u001b[31m    at Function.wrap (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:151:27)\u001b[39m\n\u001b[31m    at SourceConvertCommand.catch (C:\\Users\\max.prass\\AppData\\Local\\sfdx\\client\\7.36.0-b1c4e9c7c8\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:247:46)\u001b[39m\n\u001b[31m******\u001b[39m\n\u001b[31m\u001b[39m' ] +28s  sfdx:core TRACE Setup child 'Org' logger instance +24s
  sfdx:core TRACE Setup child 'AuthInfo' logger instance +15ms
  sfdx:core TRACE Setup child 'crypto' logger instance +1ms
  sfdx:crypto DEBUG retryStatus: undefined +28s
  sfdx:core TRACE Setup child 'keyChain' logger instance +3ms
  sfdx:keyChain DEBUG platform: win32 +28s
  sfdx:analytics Could not send command error to server due to: NamedOrgNotFound: No AuthInfo found for name brasil@32327-fix-madrid.com
    at Function.create (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\@salesforce\core\lib\sfdxError.js:141:16)
    at AuthInfo.initAuthOptions (C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\@salesforce\core\lib\authInfo.js:528:53) +28s
  lazy-require saving type cache to C:\Users\max.prass\AppData\Local\sfdx\module-types.json +29s
  lazy-require no changes to save +0ms
  sfdx:analytics using C:\Users\max.prass\AppData\Local\sfdx\analytics.log for usage error logging +3ms
  sfdx:analytics spawned usage " C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\bin\node.exe C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\@salesforce\plugin-analytics\lib\processes\logUsage " +13ms
➜  salesforce-backoffice git:(story/merge-preprod-git-with-preprod-org) ✗ C:\Users\max.prass\AppData\Local\sfdx\client\7.36.0-b1c4e9c7c8\node_modules\@salesforce\plugin-analytics\lib\processes\logUsage`
