### ISSUE TITLE
Issue with deployment

### ISSUE THREAD

**Issue by IvanLevytskyiDataArt** [forcedotcom/sfdx-core#382]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1. Run  sfdx force:source:deploy --manifest manifest/changesPackage.xml -u Production -l RunLocalTests

### Expected result

_Successfull deployment_.

### Actual result

*** Deploying with REST ***
SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\salesforce-alm\dist\lib\core\force.js:583:25)
    at Request.self.callback (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\salesforce-alm\dist\lib\core\force.js:583:25)
    at Request.self.callback (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

C:\Users\ilevytskyi\WebstormProjects\Scipher_Deployment\Salesforce\src>deployChanges ScipherProd

C:\Users\ilevytskyi\WebstormProjects\Scipher_Deployment\Salesforce\src>sfdx force:source:deploy --manifest manifest/changesPackage.xml -u ScipherProd -l RunLocalTests
*** Deploying with REST ***
SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\salesforce-alm\dist\lib\core\force.js:583:25)
    at Request.self.callback (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\salesforce-alm\dist\lib\core\force.js:583:25)
    at Request.self.callback (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\ilevytskyi\AppData\Local\sfdx\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

Additional information
Organization Edition | Enterprise Edition
Instance | CS15

SFDX CLI Version(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.89.2-d1d2614d02 win32-x64 node-v14.15.4

SFDX plugin Version(to find the version of the CLI plugin run sfdx plugins --core):
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.4.0-2 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
auth 1.4.8 (core)
config 1.2.4 (core)
generator 1.1.5 (core)
salesforcedx 51.1.1 (core)
├─ limits 1.0.4 (core)
├─ user 1.1.2 (core)
├─ schema 1.0.4 (core)
├─ apex 0.1.4 (core)
├─ templates 51.3.0 (core)
├─ custom-metadata 1.0.11 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.1.1 (core)
sfdx-cli 7.89.2 (core)
telemetry 1.1.1 (core)

OS and version:

Windows 10, Enterprise

**Comment by IvanLevytskyiDataArt** [comment]
I uninstalled Salesforce CLI and installed it from scratch. It helped.
