### ISSUE TITLE
Exception thrown after sfdx update

### ISSUE THREAD

**Issue by DarkSkull91** [forcedotcom/sfdx-core#679]
When I launch the command:

`sfdx udpate`

I get this exception:

```
- Set the SFDX_HIDE_RELEASE_NOTES env var to "true" to skip this script

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:os'
Require stack:
- /Users/xxx/.local/share/sfdx/client/7.172.0-1aa6bdf/node_modules/@oclif/plugin-version/lib/commands/version.js
- /Users/xxx/.local/share/sfdx/client/7.172.0-1aa6bdf/node_modules/@oclif/plugin-version/lib/index.js
- /Users/xxx/.local/share/sfdx/client/7.172.0-1aa6bdf/dist/cli.js
- /Users/xxx/.local/share/sfdx/client/7.172.0-1aa6bdf/bin/run
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/xxx/.local/share/sfdx/client/7.172.0-1aa6bdf/node_modules/@oclif/plugin-version/lib/commands/version.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/xxx/.local/share/sfdx/client/7.172.0-1aa6bdf/node_modules/@oclif/plugin-version/lib/commands/version.js',
    '/Users/xxx/.local/share/sfdx/client/7.172.0-1aa6bdf/node_modules/@oclif/plugin-version/lib/index.js',
    '/Users/xxx/.local/share/sfdx/client/7.172.0-1aa6bdf/dist/cli.js',
    '/Users/xxx/.local/share/sfdx/client/7.172.0-1aa6bdf/bin/run'
  ]
}

user plugins are
```

**Comment by cristiand391** [comment]
hey @DarkSkull91, please see this comment:
https://github.com/forcedotcom/cli/issues/1728#issuecomment-1260927083

**Comment by DarkSkull91** [comment]
@cristiand391 thank you very much, it works like a charm even on macOs 12.6
